# Overview {#overview}

The **Student Success Data Mart** provides the ability to review and manage analytics such as enrollment and registration metrics, count of student and faculty by registered courses, available courses for catalog building and schedule building, graduation rates and student career fulfillment of requirements, student academic standing, and faculty and student profiles.

Enrollment reports may include areas such as monitoring average class sizes, prerequisites not being met, grade distributions, and graduation eligibility. 

Reports in this category can also include aggregated statistical reports with year-to-year comparisons in several subject areas.

_With the Student Success Data Mart you can answer questions such as:_

    1) What are the enrollment metrics for this term?
    2) Can I get the Student Retention and Graduation rates year over year by Cohort, Gender and Ethnicity?
    3) What is average GPA by Institution, Career and Program?
    4) What is average time to graduate by Institution, Career and Program?
    5) What classes are scheduled for this term?
    6) Can I track and analyze the workload of the faculty?
    7) What are the Class enrollment details?
    8) What are the honors/awards details for the enrolled students?

## Where does the Student Success Data Mart source its data from?

Student Records Data Mart is related to the Academic Program Activation and Management business process. This business process includes Course Catalog, Class Scheduling, Student Career Term records and Enrollment business processes. These processes fulfill the institutions need to track course delivery, student participation through enrollments to those classes. The Academic Program activation and Management processes help manage class size, a student's enrollment in a class and track the resulting grades from the class.
