# Academic Plan Summary Star

## Description

This star contains student summary entry for a given academic plan and related academic program.

Each row of this table contains the most current information about an individual student and a particular academic plan. This fact table also contains all students that enrolled, matriculated, withdrew, or completed the academic career/program and plan in the institution.

The table is _not_ keyed by term. `Institution`, `Career`, and `Program` are indirectly part of the key since they are derived from the `Academic Plan` dimension.

There is one row of data per student (person) academic plan surrogate ID and student career number.

Records are updated frequently, whenever the student program status changed. This may include status changes from activated, admitted, discontinued, or completed.

## Helps Answer

This star may help answer the following:

- Number of enrollments by program or plan.
- Number of students who dropped out.
- Number of students in different program actions (statuses) and program action reasons by career, program, or plan.
- Number of students that completed the program/plan.
- Number of students that cancelled the program/plan.

## Star Links

This star can be built from `F_ACADPLAN_SUMM` and connects to the following tables:

```{r table-data, echo = FALSE}
input <- c("PS_D_ACAD_CAR",
"PS_D_ACAD_LOAD",
"PS_D_ACAD_ORG",
"PS_D_ACAD_PLAN",
"PS_D_ACAD_PROG",
"PS_D_ACAD_SPLAN",
"PS_D_ADMIT_TYPE",
"PS_D_AWD",
"PS_D_CAMPUS",
"PS_D_DAY",
"PS_D_DEG",
"PS_D_DEG_STAT",
"PS_D_INSTITUTION",
"PS_D_LOCATION",
"PS_D_PERSON",
"PS_D_PERSON_ADDR",
"PS_D_PERSON_ATTR",
"PS_D_PERSON_EMAIL",
"PS_D_PERSON_PHONE",
"PS_D_PROG_ACN",
"PS_D_PROG_ACN_RSN",
"PS_D_PROG_STAT",
"PS_D_STDNT_COHORT",
"PS_D_STDNT_GRP",
"PS_D_TERM",
"PS_F_ACADPLAN_SUMM",
"PS_R_ACAD_SPLAN",
"PS_R_AWD",
"PS_R_STDNT_GRP")

result = data.frame(matrix(input, ncol = 1, byrow = T), stringsAsFactors = FALSE)

knitr::kable(
  result, longtable = TRUE, booktabs = TRUE,
  caption = 'A table generated by the longtable package.'
)
```
