# Term Enrollment Star

## Description

This star contains information regarding term enrollments by student. The star provides term statistics and cumulative statistics by term, student, institution, and career. This star also provides measures such as units-in-progress, GPA, number of courses enrolled, etc.

Institution and Career are indirectly part of the key since they are deirved from the Term surrogate ID.

There is one row of data per term surrogate ID and student.


## Helps Answer

This star may help answer the following:

- Top student academic standings.
- Nmber of units in progress vs. passed by institution, career, program, or plan.
- Average number of courses a student takes per term, by career, program, or plan.
- Number of units a student is enrolled in.
- Number of full time and part time students by term, institution, campus, primary program, etc.
- Number of students taking GPA units.
- Enrollment analysis by primary program and plan, term, institution, campus career, and program.

## Star Links

This star can be built from `F_TERM_ENRLMT` and connects to the following tables:

```{r table-data-term-enrollment, echo = FALSE}
input <- c("PS_D_ACAD_LOAD",
"PS_D_ACAD_LVL",
"PS_D_ACAD_ORG",
"PS_D_ACAD_PLAN",
"PS_D_ACAD_PROG",
"PS_D_ACAD_STNDNG",
"PS_D_DAY",
"PS_D_PERSON",
"PS_D_PERSON_ADDR",
"PS_D_PERSON_ATTR",
"PS_D_PERSON_EMAIL",
"PS_D_PERSON_PHONE",
"PS_D_PROG_ACN",
"PS_D_PROG_ACN_RSN",
"PS_D_PROG_STAT",
"PS_D_RSDNCY",
"PS_D_STDNT_COHORT",
"PS_D_STDNT_GRP",
"PS_D_TERM",
"PS_D_YEAR",
"PS_R_PERSON_RSDNCY",
"PS_R_STDNT_GRP")

result = data.frame(matrix(input, ncol = 1, byrow = T), stringsAsFactors = FALSE)

knitr::kable(
  result, longtable = TRUE, booktabs = TRUE,
  caption = 'A table generated by the longtable package.'
)
```
